# Default values for Rebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appMode: prod
  dbPassword: "{{ randAlphaNum 5 }}"
  nfsServerHost: "nfs-server-host"
  nfsPath: "nfs-path" # nfs volume path
  cicdServerHost: "cicd-server-host"
  cicdPath: "cicd-path" # cicd server path
  domainHost: "https://dev.brdnc.co.kr/"
  emailHost: "smtp-server.com" # your-smtp-server.com
  emailHostUser: "email@example.com" # 'your-email@example.com
  emailHostPassword: "{{ randAlphaNum 5 }}" # your-email-password
  emailDefaultSender: "email@example.com"

nameOverride: ""
fullnameOverride: ""

mariadb:
  volumes:
    nfsServerHost: ""

nginx:
  service:
    type: LoadBalancer
    port: 8880
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "100M"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "host-path" # Host address
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: web-devbox-kr-cert
        hosts:
          - "host-path" # Host address

