apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}-service
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      name: mariadb-port
  clusterIP: None
  selector:
    app: mariadb
