apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nfs-client-provisioner
#  labels:
#    app: nfs-client-provisioner
#spec:
#  replicas: 1
#  strategy:
#    type: Recreate
#  selector:
#    matchLabels:
#      app: nfs-client-provisioner
#  template:
#    metadata:
#      labels:
#        app: nfs-client-provisioner
#    spec:
#      serviceAccountName: nfs-client-provisioner
#      containers:
#        - name: nfs-client-provisioner
#          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
#          volumeMounts:
#            - name: nfs-client-root
#              mountPath: /persistentvolumes
#          env:
#            - name: PROVISIONER_NAME
#              value: k8s-sigs.io/nfs-subdir-external-provisioner
#            - name: NFS_SERVER
#              value: 49.247.26.88
#            - name: NFS_PATH
#              value: /mnt/nfs/rebs/prod/volume
#      volumes:
#        - name: nfs-client-root
#          nfs:
#            server: 49.247.26.88
#            path: /mnt/nfs/rebs/prod/volume
