name: _Initial [Prod Step2]

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# job은 사용자가 정한 플랫폼을 통해 steps 라는 일련의 과정을 실행.
# 여러 개의 job 을 사용할 수 있으며, 여러 개의 job 을 사용할 때는 서로 정보도 교환 가능.
# 각각 독립적으로도 실행 가능.
jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      # 레파지터리 체크 아웃
      - name: Check out source code
        uses: actions/checkout@v3

      # Django collectstatic & migrate
      - name: Django collectstatic & migrate (ci/cd server)
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USER }}
          password: ${{ secrets.CICD_PASS }}
          command: |
            web_pod=$(kubectl get pod -n prod-hrebs | grep web | cut -d ' ' -f1)
            kubectl exec -it -n prod-hrebs $web_pod -- mkdir -p media
            kubectl exec -it -n prdd-hrebs $web_pod -- chmod -R 755 media
            kubectl exec -it -n prod-hrebs $web_pod -- cp _config/settings/local.py _config/settings/prod.py
            kubectl exec -it -n prod-hrebs $web_pod -- sed -i 's/True/False/g' _config/settings/prod.py
            kubectl exec -it -n prod-hrebs $web_pod -- sed -i "2,6 s/*/${{ secrets.DOMAIN_NAME }}', 'www.${{ secrets.DOMAIN_NAME }}', 'api.${{ secrets.DOMAIN_NAME }}/g" _config/settings/prod.py
            kubectl exec -it -n prod-hrebs $web_pod -- sed -i '/CSRF_TRUSTED_ORIGINS/d' _config/settings/prod.py | sed '/^$/d'
            kubectl exec -it -n prod-hrebs $web_pod -- python manage.py collectstatic --no-input
            kubectl exec -it -n prod-hrebs $web_pod -- python manage.py makemigrations accounts book cash company contract document items notice payment project rebs
            kubectl exec -it -n prod-hrebs $web_pod -- python manage.py migrate

      # Node.js 사용
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # pnpm use
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      # node_modules 캐싱
      - name: Cache vue node
        uses: actions/cache@v3
        id: cache_vue
        with:
          path: ./app/vue/node_modules
          key: pnpm-packages-${{ hashFiles('**/pnpm.lock') }}

      # node_modules 변화기 있으면 빌드
      - name: Install Dependencies
        if: steps.cache_vue.outputs.cache-hit != 'true'
        run: cd app/vue && pnpm i

      #      - run: pnpm lint
      #        # `if: ${{ always() }}`
      #        # 만약 `pnpm lint`라는 곳에서 에러가 났을 경우 이후 build를 실행하지 않고 해당 workflow가 종료됨.
      #        # `if: ${{ always() }}`라는 문법을 사용 시 `pnpm lint`라는 곳에서 에러가 나도
      #        # 이후의 build까지 다 실행을 해보고 난 뒤 종료 하므로 모든 테스트 스크립트에 `if: ${{ always() }}`를 붙임.
      #        if: ${{ always() }}

      - run: cd app/vue && pnpm build && pnpm docs:build
        if: ${{ always() }}

      # Docs deploy
      - name: Docs Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/vue/docs/.vitepress/dist

      # Source to NFS server copy transfer
      - name: Copy Vue -> django static/dist (NFS server)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NFS_HOST }}
          username: ${{ secrets.NFS_USER }}
          password: ${{ secrets.NFS_PASS }}
          source: 'app/django'
          target: ${{ secrets.NFS_PATH }}/prod/

      # node_modules 캐싱
      - name: Cache svelte node
        uses: actions/cache@v3
        id: cache_svelte
        with:
          path: ./app/svelte/node_modules
          key: pnpm-packages-${{ hashFiles('**/pnpm.lock') }}

      # node_modules 변화기 있으면 빌드
      - name: Install Dependencies
        if: steps.cache_svelte.outputs.cache-hit != 'true'
        run: cd app/svelte && pnpm i

      - run: cd app/svelte && pnpm build
        if: ${{ always() }}

      # Source to NFS server copy transfer
      - name: Copy Svelte -> django static/dist (NFS server)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NFS_HOST }}
          username: ${{ secrets.NFS_USER }}
          password: ${{ secrets.NFS_PASS }}
          source: 'app/django'
          target: ${{ secrets.NFS_PATH }}/prod/

      # slack --> notification
      - name: Send slack when failed
        if: ${{ failure() }}                    # 실패했을 때 실행
        uses: ./.github/actions/slack-notify    # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        if: ${{ success() }}                    # 성공할 때만 실행
        uses: ./.github/actions/slack-notify
        with:
          status: success   # status input은 받는 쪽에서 default 값을 정해놨기 때문에 success일 때만 전달.
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
