name: DB_backup

on:
  schedule:
    - cron: "0 16 * * 2-6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# job은 사용자가 정한 플랫폼을 통해 steps 라는 일련의 과정을 실행.
# 여러 개의 job 을 사용할 수 있으며, 여러 개의 job 을 사용할 때는 서로 정보도 교환 가능.
# 각각 독립적으로도 실행 가능.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 레파지터리 체크 아웃
      - name: Check out source code
        uses: actions/checkout@v3

      # data to server copy transfer
      - name: Copy backup script to CI/CD server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          source: 'volume/backups'
          target: '/mnt/nfs/prod'

      - run: date

      # mysql pod --> database bakcup
      - name: database backup
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          command: |
            master_pod=$(kubectl get pod -n prod-hrebs | grep master | cut -d ' ' -f1)
            kubectl exec -it -n prod-hrebs $master_pod -- sh /var/backups/script.sh

      # slack --> notification
      - name: Send slack when failed
        if: ${{ failure() }}                    # 실패했을 때 실행
        uses: ./.github/actions/slack-notify    # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
